
server:
  port: 9090

spring:
 jpa:
  database: POSTGRESQL
  show-sql: true
  hibernate:
    ddl-auto: create-drop

 datasource:
  platform: postgres
  url: jdbc:postgresql://localhost/postgres
  username: keycloak
  password: password
  driverClassName: org.postgresql.Driver

keycloak:
  realm: service
  auth-server-url: http://localhost:8081/auth
  resource: springboot-keycloak
  public-client: true
  bearer-only: true

